### ISSUE TITLE
login password

### ISSUE THREAD

**Issue by iconbloom** [bishosilwal/clinic-management-system#1]
Hi,
what is the admin and  user login password

**Comment by bishosilwal** [comment]
There is .env file in root folder . you can change
 DB_DATABASE= hms
DB_USERNAME=root
DB_PASSWORD= root

these line and use any database name that is already created and your
database username and password. Mysql database need to be installed in your
system. I assume you already knew how to run laravel project. So if you
encounter any problem please let me know.

**Comment by kelvinric123** [comment]
Hi dear bisho silwal, i also facing the same problem that i cant login
i tried with 
username= admin@admin.com
password = admin
but cannot. can you kindly assist me?

**Comment by joepassa** [comment]
Hi, I wanted to try it but it does not allow me to access with te 
username= admin@admin.com
password = admin
could you access help me.


Thanks

![1web](https://user-images.githubusercontent.com/51215327/58668300-eb2ebb80-830e-11e9-9374-0791d89c0121.png)

![1db](https://user-images.githubusercontent.com/51215327/58668414-31841a80-830f-11e9-9c95-35d8b6e81cb8.png)

**Comment by esprit7** [comment]
hi all please you did how to get access because i live the same thing

**Comment by esprit7** [comment]
> Hi, I wanted to try it but it does not allow me to access with te
> username= [admin@admin.com](mailto:admin@admin.com)
> password = admin
> could you access help me.
> 
> Thanks
> 
> ![1web](https://user-images.githubusercontent.com/51215327/58668300-eb2ebb80-830e-11e9-9374-0791d89c0121.png)
> 
> ![1db](https://user-images.githubusercontent.com/51215327/58668414-31841a80-830f-11e9-9c95-35d8b6e81cb8.png)


finally the solution is what's so big

**Comment by esprit7** [comment]
> There is .env file in root folder . you can change DB_DATABASE= hms DB_USERNAME=root DB_PASSWORD= root these line and use any database name that is already created and your database username and password. Mysql database need to be installed in your system. I assume you already knew how to run laravel project. So if you encounter any problem please let me know.


hello sir can help me? I can not get access

**Comment by bishosilwal** [comment]
Dear Sir, Please see my github repo  clinic-management-system. I have
updated readme file. Thank you

**Comment by bishosilwal** [comment]
After importing database file from ./database/hms.sql , you can use username: Superadmin and password: superadmin

**Comment by esprit7** [comment]
thank you


Google+ : Emmanuel Foka
Twitter : Emmanuel Foka


Le dim. 9 juin 2019 à 16:16, bisho silwal <notifications@github.com> a
écrit :
